#!/bin/bash
sudo su
apt update -y
apt install -y apache2 unzip wget pipx
pipx install gdown
pipx ensurepath
source ~/.bashrc
systemctl start apache2
systemctl enable apache2

# Download the template
gdown 1H9RaSCEx1pvBupx2qcDvcN1E7YLdcl2B -O neogym.zip

# Unzip the file
unzip -o neogym.zip

# Copy files to Apache web directory
cp -r neogym-html/* /var/www/html/

# Restart Apache
systemctl restart apache2
