#!/bin/bash
sudo su
apt update -y
apt install -y apache2 unzip wget
systemctl start apache2
systemctl enable apache2

# Download the template
wget -O neogym.zip "https://html.design/downloads/13468/?tmstv=1762471543"

# Unzip the file
unzip -o neogym.zip

# Copy files to Apache web directory
cp -r neogym-html/* /var/www/html/

# Restart Apache
systemctl restart apache2
